name: Test container structure

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  REGISTRY: docker.io
  IMAGE_NAME: appwrite/base

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: arm64
            os: ubuntu-24.04-arm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build an image from Dockerfile
        run: |
          docker image build --tag utopia-base-test php-${{ matrix.php-versions }}/.

      - name: Run container structure tests
        uses: plexsystems/container-structure-test-action@c0a028aa96e8e82ae35be556040340cbb3e280ca # v0.3.0
        with:
          image: utopia-base-test
          config: php-${{ matrix.php-versions }}/tests.yaml
